import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export const runtime = "nodejs";

/** Gated download: requires an active subscription. Records the download
 *  (which mints a certificate number) and redirects to the audio file. */
export async function GET(req: Request) {
  const url = new URL(req.url);
  const trackId = url.searchParams.get("track");
  const origin = process.env.NEXT_PUBLIC_APP_URL || url.origin;

  if (!trackId) return NextResponse.redirect(`${origin}/`);

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.redirect(`${origin}/?auth=required`);

  const admin = createAdminClient();
  const { data: profile } = await admin
    .from("profiles")
    .select("plan, subscription_status")
    .eq("id", user.id)
    .maybeSingle();

  const active = profile?.subscription_status === "active" || profile?.subscription_status === "trialing";
  if (!active) return NextResponse.redirect(`${origin}/?upgrade=1#pricing`);

  const { data: track } = await supabase
    .from("tracks")
    .select("id, title, audio_path")
    .eq("id", trackId)
    .maybeSingle();

  if (!track?.audio_path) return NextResponse.redirect(`${origin}/?download=unavailable`);

  // Record the download (certificate number is auto-generated by the DB).
  await admin.from("downloads").insert({
    user_id: user.id,
    track_id: track.id,
    track_title: track.title,
    plan: profile?.plan ?? null,
  });

  // Force download with a clean filename via Supabase Storage's download param.
  const base = (track.audio_path as string).split("?")[0];
  const ext = (base.split(".").pop() || "mp3").toLowerCase();
  const filename = `${(track.title as string).replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.${ext}`;
  const sep = (track.audio_path as string).includes("?") ? "&" : "?";
  return NextResponse.redirect(`${track.audio_path}${sep}download=${encodeURIComponent(filename)}`);
}
