import type { Metadata } from "next";
import "./globals.css";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "https://zoundlist.com";

// Brand: Zoundlist (operated by JM Creativos LLC). Domain: zoundlist.com.
export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),

  title: {
    default: "Zoundlist — Música para lo que estás creando",
    template: "%s | Zoundlist",
  },

  description:
    "Música cinematográfica, editorial y ambient creada con IA y curada a mano. " +
    "Para video, podcast, iglesias y marcas. Licencia incluida en cada descarga.",

  keywords: [
    "música para videos",
    "música IA",
    "música para YouTube",
    "música para podcast",
    "música sin copyright",
    "música para creadores",
    "música worship",
    "licencia musical",
    "AI music",
    "royalty free music",
  ],

  openGraph: {
    type: "website",
    locale: "es_PR",
    url: APP_URL,
    siteName: "Zoundlist",
    title: "Zoundlist — Música para lo que estás creando",
    description:
      "Música cinematográfica creada con IA y curada a mano. " +
      "Licencia incluida en cada descarga.",
    // OG image is generated by app/opengraph-image.tsx
  },

  twitter: {
    card: "summary_large_image",
    title: "Zoundlist — Música para lo que estás creando",
    description: "Música cinematográfica creada con IA. Licencia incluida.",
    // Twitter image is generated by app/twitter-image.tsx
    // site: "@zoundlist", // uncomment when account exists
  },

  alternates: {
    canonical: APP_URL,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },

  // Google Search Console (URL-prefix): set GOOGLE_SITE_VERIFICATION in Vercel.
  verification: process.env.GOOGLE_SITE_VERIFICATION
    ? { google: process.env.GOOGLE_SITE_VERIFICATION }
    : undefined,

  // Web-only. No mobile app metadata.
  // No appLinks, no apple-app-site-association, no appleWebApp.
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Zoundlist",
  url: APP_URL,
  logo: `${APP_URL}/zoundlist-icon.png`,
  description:
    "Plataforma de descubrimiento musical: música creada con IA y curada a mano para video, podcast, iglesias y marcas. Licencia incluida en cada descarga.",
  founder: { "@type": "Organization", name: "JM Creativos LLC" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://api.fontshare.com" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,600,700,900&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
